### ISSUE TITLE
Mejorar SgConf

### ISSUE THREAD

**Issue by jcguarinpenaranda** [mmuriel/sg-syncer#1]
Hola,

He realizado una modificación en SgConf.js, que permitiría que el alojamiento de los videos y de la base de datos se realice con rutas relativas a la carpeta del proyecto.

Mi cambio propuesto es este:

``` javascript
var SgCnf = {
    sgtoken : 'COL102',
    profile : 'client', //Valores posibles: server|client
    torrentOpt : {
          //announce: [],              // Torrent trackers to use (added to list in .torrent or magnet uri)
          //getAnnounceOpts: Function, // Custom callback to allow sending extra parameters to the tracker
          maxWebConns: 8,       // Max number of simultaneous connections per web seed [default=4]
          path: __dirname+'../tmp/videos/',              // Folder to download files to (default=`/tmp/webtorrent/`)
          //store: Function            // Custom chunk store (must follow [abstract-chunk-store](https://www.npmjs.com/package/abstract-chunk-store) API)
        },
    pathToSource: __dirname+'../tmp/videos/', //Ruta en el sistema de archivos que se "vigilará" por archivos nuevos
    pathToDest: __dirname+'../tmp/videos/', //Ruta hacia donde se depositarán los arhivos en la red bittorrent
    socketEndPoint:'http://s12.sientifica.com:9000',//Socketio server URL
    pathToDb: __dirname+'/../db/sgdb.db'//Ruta hacia el archivos que almacena la DB tipo sqlite
};
```

De esta manera, no se necesita saber la ruta absoluta donde se quiere guardar la base de datos, ni los videos, sino que el programa la determina automáticamente relativo a dónde se esté ejecutando el proyecto.

P.ej: se podría tener el proyecto en la ruta /home/juan/sg-syncer, y la base de datos quedaría guardada en /home/juan/sg-syncer/db/sgdb.db, y los videos alojados en /home/juan/sg-syncer/tmp/videos

Entiendo que el token es algo que cambiaría de cliente a cliente. Esto se podría reemplazar fácilmente si el parámetro sgtoken recibiera el resultado de una función que por ejemplo genere un hash basada en la fecha del dispositivo, y la ruta en la que esté el script.

Esto lo pongo como issue, porque no sé cuáles sean las consideraciones actuales para este token y si la ruta relativa dañaría el servidor en producción

**Comment by mmuriel** [comment]
Buen punto Juan, lo de las rutas relativas me parece perfecto y no tiene nada que ver con la definción del token, es decir, que podría implementar lo de las rutas relativas.

**Comment by mmuriel** [comment]
Juan, esta mañana ya descansado, recordé que esas rutas hacia las carpetas donde residen los videos no pueden ser relativas al proyecto, o al menos no deberían serlo, por que el destino final de los mismo (los videos) no están en la ruta del proyecto en las máquinas del entorno de producción, lo mejor es dejar las rutas absolutas en el sistema de archivos.

**Comment by mmuriel** [comment]
La única que si debe ser relativa al proyecto es la que apunta al almacenamiento de la DB, esa si está dentro del proyecto, voy a aplicar el cambio sugerido ;)

**Comment by jcguarinpenaranda** [comment]
Con gusto. Estaba pensando que como ya tienes manera de saber si el programa ha sido invocado para cliente o servidor, puedes hacer que para los clientes la ruta sea relativa, y para el servidor la ruta que necesitas en producción
